### ISSUE TITLE
Problem with HL and CA data

### ISSUE THREAD

**Issue by James-Thorson** [ices-tools-prod/icesDatras#5] opened 2016-08-11 17:16 UTC
Hi all,

I'm exploring adding icesDatras as a depenency to `FishData` (https://github.com/James-Thorson/FishData), and its working for getting haul meta-data, but I'm finding problems when querying length or age data:

``` R
> dim( getHHdata(survey="NS-IBTS", year=2014, quarter=1) )
[1] 352  61
> dim( getHLdata(survey="NS-IBTS", year=2000, quarter=1) )
[1] 0 0
> dim( getCAdata(survey="NS-IBTS", year=2000, quarter=1) )
[1] 0 0
```

some sleuthing seems to show that its a problem in the call to the API, during

``` R
    out <- curlDatras(url = url)
    out <- parseDatras(out)
```

in e.g, `getHLdata`.  Any thoughts on what might be happening?

**Comment by colinpmillar** [comment] 2016-08-11 18:47
Thanks Jim,  I think the problem is that the API returns nothing - see:

[https://datras.ices.dk/WebServices/DATRASWebService.asmx/getHLdata?survey=NS-IBTS&year=2015&quarter=1](https://datras.ices.dk/WebServices/DATRASWebService.asmx/getHLdata?survey=NS-IBTS&year=2015&quarter=1)

So, techincally not an issue with this package, but an issue with the API itself.  I have raised this with the Data Centre here at ICES.
Thanks for raising this.

**Comment by James-Thorson** [comment] 2016-08-11 19:20
Makes sense.  I don't know the DATRAS API, and haven't done any homework
really on how it works.  But:  is it possible to automate some check
whether its working as expected or not?  It would be a shame for a user to
conclude there's no length/age data available for a given
quarter/year/survey when there really is.  Perhaps `getHHdata` could check
a given quarter/year/survey combo, and if there's data available but the
age/length API isn't returning anything then it gives a warning/error
message?

As always, please suggest helpful coding for me...

jim

**Comment by colinpmillar** [comment] 2016-08-11 19:24
Yeah  think you are right - and that would be the sensible solution to this issue.  

We know there should be data, because before we send the request, we check that DATRAS says there are records for that survey, year and quarter combinations.  

Will implement and close, probably the start of next week.

**Comment by colinpmillar** [comment] 2016-08-12 16:22
Hi, it seems that this was an internal issue due to updated column names in the database itself that had not been carried through to the API, it should be fixed now.

**Comment by James-Thorson** [comment] 2016-08-12 16:38
Great!  Yes, I can confirm that I'm now getting reasonable output from
`getHLdata`.

One additional question:  many surveys in North America report and analyzes
survey catch rates in units weight per area.  However, Datras doesn't
appear to report weight for each specimen in the `getHLdata` output.  If
this were available, `FishData` (or `icesDatras`) could sum across
specimens weights in each tow to get total weight by species per tow, for
comparison with N American data.

Would someone at ICES be willing to work with me to make automated code
that uses weight-length relationships to convert specimen length to weight?


jim

**Comment by colinpmillar** [comment] 2019-03-07 08:12
Continue length weight issue: Length weight from DATRAS #26

**Closed by colinpmillar** 2019-03-07 08:12 UTC
